# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.26.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.26.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/unconvrs/CLionProjects/crystal-cage-identification

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/unconvrs/CLionProjects/crystal-cage-identification

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.26.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.26.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/unconvrs/CLionProjects/crystal-cage-identification/CMakeFiles /Users/unconvrs/CLionProjects/crystal-cage-identification//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/unconvrs/CLionProjects/crystal-cage-identification/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named crystal_cage_identification

# Build rule for target.
crystal_cage_identification: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 crystal_cage_identification
.PHONY : crystal_cage_identification

# fast build rule for target.
crystal_cage_identification/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crystal_cage_identification.dir/build.make CMakeFiles/crystal_cage_identification.dir/build
.PHONY : crystal_cage_identification/fast

AlgCage.o: AlgCage.cpp.o
.PHONY : AlgCage.o

# target to build an object file
AlgCage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crystal_cage_identification.dir/build.make CMakeFiles/crystal_cage_identification.dir/AlgCage.cpp.o
.PHONY : AlgCage.cpp.o

AlgCage.i: AlgCage.cpp.i
.PHONY : AlgCage.i

# target to preprocess a source file
AlgCage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crystal_cage_identification.dir/build.make CMakeFiles/crystal_cage_identification.dir/AlgCage.cpp.i
.PHONY : AlgCage.cpp.i

AlgCage.s: AlgCage.cpp.s
.PHONY : AlgCage.s

# target to generate assembly for a file
AlgCage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crystal_cage_identification.dir/build.make CMakeFiles/crystal_cage_identification.dir/AlgCage.cpp.s
.PHONY : AlgCage.cpp.s

AlgCage_CageViaCup.o: AlgCage_CageViaCup.cpp.o
.PHONY : AlgCage_CageViaCup.o

# target to build an object file
AlgCage_CageViaCup.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crystal_cage_identification.dir/build.make CMakeFiles/crystal_cage_identification.dir/AlgCage_CageViaCup.cpp.o
.PHONY : AlgCage_CageViaCup.cpp.o

AlgCage_CageViaCup.i: AlgCage_CageViaCup.cpp.i
.PHONY : AlgCage_CageViaCup.i

# target to preprocess a source file
AlgCage_CageViaCup.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crystal_cage_identification.dir/build.make CMakeFiles/crystal_cage_identification.dir/AlgCage_CageViaCup.cpp.i
.PHONY : AlgCage_CageViaCup.cpp.i

AlgCage_CageViaCup.s: AlgCage_CageViaCup.cpp.s
.PHONY : AlgCage_CageViaCup.s

# target to generate assembly for a file
AlgCage_CageViaCup.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crystal_cage_identification.dir/build.make CMakeFiles/crystal_cage_identification.dir/AlgCage_CageViaCup.cpp.s
.PHONY : AlgCage_CageViaCup.cpp.s

Auxilaryfun.o: Auxilaryfun.cpp.o
.PHONY : Auxilaryfun.o

# target to build an object file
Auxilaryfun.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crystal_cage_identification.dir/build.make CMakeFiles/crystal_cage_identification.dir/Auxilaryfun.cpp.o
.PHONY : Auxilaryfun.cpp.o

Auxilaryfun.i: Auxilaryfun.cpp.i
.PHONY : Auxilaryfun.i

# target to preprocess a source file
Auxilaryfun.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crystal_cage_identification.dir/build.make CMakeFiles/crystal_cage_identification.dir/Auxilaryfun.cpp.i
.PHONY : Auxilaryfun.cpp.i

Auxilaryfun.s: Auxilaryfun.cpp.s
.PHONY : Auxilaryfun.s

# target to generate assembly for a file
Auxilaryfun.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crystal_cage_identification.dir/build.make CMakeFiles/crystal_cage_identification.dir/Auxilaryfun.cpp.s
.PHONY : Auxilaryfun.cpp.s

GeneralCage.o: GeneralCage.cpp.o
.PHONY : GeneralCage.o

# target to build an object file
GeneralCage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crystal_cage_identification.dir/build.make CMakeFiles/crystal_cage_identification.dir/GeneralCage.cpp.o
.PHONY : GeneralCage.cpp.o

GeneralCage.i: GeneralCage.cpp.i
.PHONY : GeneralCage.i

# target to preprocess a source file
GeneralCage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crystal_cage_identification.dir/build.make CMakeFiles/crystal_cage_identification.dir/GeneralCage.cpp.i
.PHONY : GeneralCage.cpp.i

GeneralCage.s: GeneralCage.cpp.s
.PHONY : GeneralCage.s

# target to generate assembly for a file
GeneralCage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crystal_cage_identification.dir/build.make CMakeFiles/crystal_cage_identification.dir/GeneralCage.cpp.s
.PHONY : GeneralCage.cpp.s

HBondedMol.o: HBondedMol.cpp.o
.PHONY : HBondedMol.o

# target to build an object file
HBondedMol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crystal_cage_identification.dir/build.make CMakeFiles/crystal_cage_identification.dir/HBondedMol.cpp.o
.PHONY : HBondedMol.cpp.o

HBondedMol.i: HBondedMol.cpp.i
.PHONY : HBondedMol.i

# target to preprocess a source file
HBondedMol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crystal_cage_identification.dir/build.make CMakeFiles/crystal_cage_identification.dir/HBondedMol.cpp.i
.PHONY : HBondedMol.cpp.i

HBondedMol.s: HBondedMol.cpp.s
.PHONY : HBondedMol.s

# target to generate assembly for a file
HBondedMol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crystal_cage_identification.dir/build.make CMakeFiles/crystal_cage_identification.dir/HBondedMol.cpp.s
.PHONY : HBondedMol.cpp.s

InOut.o: InOut.cpp.o
.PHONY : InOut.o

# target to build an object file
InOut.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crystal_cage_identification.dir/build.make CMakeFiles/crystal_cage_identification.dir/InOut.cpp.o
.PHONY : InOut.cpp.o

InOut.i: InOut.cpp.i
.PHONY : InOut.i

# target to preprocess a source file
InOut.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crystal_cage_identification.dir/build.make CMakeFiles/crystal_cage_identification.dir/InOut.cpp.i
.PHONY : InOut.cpp.i

InOut.s: InOut.cpp.s
.PHONY : InOut.s

# target to generate assembly for a file
InOut.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crystal_cage_identification.dir/build.make CMakeFiles/crystal_cage_identification.dir/InOut.cpp.s
.PHONY : InOut.cpp.s

Planes.o: Planes.cpp.o
.PHONY : Planes.o

# target to build an object file
Planes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crystal_cage_identification.dir/build.make CMakeFiles/crystal_cage_identification.dir/Planes.cpp.o
.PHONY : Planes.cpp.o

Planes.i: Planes.cpp.i
.PHONY : Planes.i

# target to preprocess a source file
Planes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crystal_cage_identification.dir/build.make CMakeFiles/crystal_cage_identification.dir/Planes.cpp.i
.PHONY : Planes.cpp.i

Planes.s: Planes.cpp.s
.PHONY : Planes.s

# target to generate assembly for a file
Planes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crystal_cage_identification.dir/build.make CMakeFiles/crystal_cage_identification.dir/Planes.cpp.s
.PHONY : Planes.cpp.s

PolygonAreas.o: PolygonAreas.cpp.o
.PHONY : PolygonAreas.o

# target to build an object file
PolygonAreas.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crystal_cage_identification.dir/build.make CMakeFiles/crystal_cage_identification.dir/PolygonAreas.cpp.o
.PHONY : PolygonAreas.cpp.o

PolygonAreas.i: PolygonAreas.cpp.i
.PHONY : PolygonAreas.i

# target to preprocess a source file
PolygonAreas.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crystal_cage_identification.dir/build.make CMakeFiles/crystal_cage_identification.dir/PolygonAreas.cpp.i
.PHONY : PolygonAreas.cpp.i

PolygonAreas.s: PolygonAreas.cpp.s
.PHONY : PolygonAreas.s

# target to generate assembly for a file
PolygonAreas.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crystal_cage_identification.dir/build.make CMakeFiles/crystal_cage_identification.dir/PolygonAreas.cpp.s
.PHONY : PolygonAreas.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crystal_cage_identification.dir/build.make CMakeFiles/crystal_cage_identification.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crystal_cage_identification.dir/build.make CMakeFiles/crystal_cage_identification.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crystal_cage_identification.dir/build.make CMakeFiles/crystal_cage_identification.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... crystal_cage_identification"
	@echo "... AlgCage.o"
	@echo "... AlgCage.i"
	@echo "... AlgCage.s"
	@echo "... AlgCage_CageViaCup.o"
	@echo "... AlgCage_CageViaCup.i"
	@echo "... AlgCage_CageViaCup.s"
	@echo "... Auxilaryfun.o"
	@echo "... Auxilaryfun.i"
	@echo "... Auxilaryfun.s"
	@echo "... GeneralCage.o"
	@echo "... GeneralCage.i"
	@echo "... GeneralCage.s"
	@echo "... HBondedMol.o"
	@echo "... HBondedMol.i"
	@echo "... HBondedMol.s"
	@echo "... InOut.o"
	@echo "... InOut.i"
	@echo "... InOut.s"
	@echo "... Planes.o"
	@echo "... Planes.i"
	@echo "... Planes.s"
	@echo "... PolygonAreas.o"
	@echo "... PolygonAreas.i"
	@echo "... PolygonAreas.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

